### ISSUE TITLE
When installed, Yeoman can't find this generator

### ISSUE THREAD

**Issue by z-ax** [banderson/generator-flux-react#1]
Others like `generator-webapp` work/appear finely.

My `npm -g root` is `/usr/local/lib/node_modules` and I have OSX 10.9.4. I'm running all `-g` commands without `sudo`. Yeoman v1.2.1.
Generator doesn't appear in `yo` command list after installation (no warnings, etc), can't run `yo flux`.
Tried to install via both `npm` and `yo`.

**Comment by banderson** [comment]
Inactive for 4+ months, closing!
