### ISSUE TITLE
react-bootstrap option

### ISSUE THREAD

**Issue by ryanlitalien** [banderson/generator-flux-react#11]
Hi Ben, any thoughts of providing a react-bootstrap option? And possibly a basic example page with a few components?

```
yo flux:component-bootstrap BootstrapComponentName
```
https://github.com/react-bootstrap/react-bootstrap

**Comment by banderson** [comment]
Mr. @ryanlitalien!! That is very much on my radar. I'm looking to offer a couple different UI options:

* [react-bootstrap](http://react-bootstrap.github.io/)
* [material UI](http://material-ui.com/)
* and maybe [TouchstoneJS](http://touchstonejs.io/) as a mobile option

Maybe if you 'star' my project I'll bump this in priority :) :money_with_wings:

**Comment by banderson** [comment]
@ryanlitalien there is basic support for React Bootstrap and Material UI frameworks in the [latest published version (0.3.0)](https://www.npmjs.com/package/generator-flux). It simply loads and configures everything, but not much in terms of scaffolded UI. That will get better over time.

**Comment by ryanlitalien** [comment]
Thanks @banderson, appreciate the quick turnaround!
