### ISSUE TITLE
Missing components in react

### ISSUE THREAD

**Issue by jmsherry** [banderson/generator-flux-react#18]
I used the generator and opted for react-bootstrap, but keep getting missing dependancies for 'input', 'button', 'ListGroup' and 'ListGroupItem' - am I doing something wrong?

Browserify Error { [Error: Cannot find module 'react-bootstrap/Input' from '/Users/jamessherry/sites/react/src/js/components']

**Comment by peh** [comment]
i experienced the same issue

**Comment by peh** [comment]
it should be https://github.com/react-bootstrap/react-bootstrap/issues/388 that causes this
downgrading to react-bootstrap 0.14.1 seems to fix this issue

**Comment by banderson** [comment]
Thanks for helping out @peh! This is the unfortunate side of supporting these external UI Frameworks. I'm considering yanking them out and just including instructions for adding in after project generation due to this and issues like #16

**Comment by banderson** [comment]
It looks like this will be fixed in the next path release, landing this weekend. I'll followup once it officially lands.

**Comment by banderson** [comment]
@nickcs patch version 0.3.3 just landed on NPM. Let me know if this is still broken for you!

**Comment by jmsherry** [comment]
Thanks guys. I'll take a look and comment if it's still and issue. :)
