### ISSUE TITLE
No deps or dev-deps in package.json

### ISSUE THREAD

**Issue by MattMcFarland** [banderson/generator-flux-react#22]
after running `yo flux`, the package json file does not have devDependencies or dependencies in it at all, it's completely empty.  Anything I'm doing wrong?

**Comment by MattMcFarland** [comment]
Seems that starting over from scratch solved the problem... weird... works though!

**Comment by banderson** [comment]
Thanks for reporting this. I've been having some reports that npm install errors without completing, leading to errors like this. I don't think we're doing anything abnormal in this generator, but I'll need to dig in or find another approach if this keeps happening! Thanks again.

**Comment by EwanValentine** [comment]
I'm still getting issues with this, had to install them all manually
