### ISSUE TITLE
Replace 6to5ify with babelify

### ISSUE THREAD

**Issue by mattdeboard** [banderson/generator-flux-react#24]
Easily sorted manually, but since [6to5ify has been replaced by babelify](https://babeljs.io/blog/2015/02/15/not-born-to-die/) it would be useful to update the template.

**Comment by banderson** [comment]
Hi @mattdeboard, are you on the latest version (0.3.2)? This should've been fixed by #19. Let me know if you're still seeing this issue on the latest verison.
