### ISSUE TITLE
ES 6 style generators ?

### ISSUE THREAD

**Issue by darkyen** [banderson/generator-flux-react#26]
Something like this ? https://github.com/darkyen/awwfood/blob/master/src/js/components/Header.jsx 

It could be a config when generating the repo as we are using babel anyways why not generators with es6 syntax?

**Comment by banderson** [comment]
You read my mind, this is in the works :)

We're using some ES6 things like [enhanced object literals](https://github.com/banderson/generator-flux-react/blob/master/store/templates/store.js#L11) and [arrow functions](https://github.com/banderson/generator-flux-react/blob/master/app/templates/js/components/naked/TaskList.jsx#L15-L17), but they are very few and far between. This will likely happen this weekend!

**Comment by banderson** [comment]
It's a start... Happy ES6'ing!

https://github.com/banderson/generator-flux-react/commit/9ffbcd319f9883880184120cb490020ee357ef8e
