### ISSUE TITLE
Uncaught TypeError: Cannot read property 'component' of undefined

### ISSUE THREAD

**Issue by mtbvang** [banderson/generator-flux-react#35]
Hi,

I ran the generator and got the following error. Can anyone point me in the right direction to debug this?

Uncaught TypeError: Cannot read property 'component' of undefined
getThemeButton @ index.js:7179
getStyles @ index.js:7191
render @ index.js:7241
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ index.js:20653ReactCompositeComponentMixin._renderValidatedComponent @ index.js:20680ReactPerf.measure.wrapper @ index.js:27212ReactCompositeComponentMixin.mountComponent @ index.js:20101ReactPerf.measure.wrapper @ index.js:27212ReactReconciler.mountComponent @ index.js:28027ReactMultiChild.Mixin.mountChildren @ index.js:26651ReactDOMComponent.Mixin._createContentMarkup @ index.js:21421ReactDOMComponent.Mixin.mountComponent @ index.js:21331ReactReconciler.mountComponent @ index.js:28027ReactCompositeComponentMixin.mountComponent @ index.js:20111ReactPerf.measure.wrapper @ index.js:27212ReactReconciler.mountComponent @ index.js:28027ReactCompositeComponentMixin.mountComponent @ index.js:20111ReactPerf.measure.wrapper @ index.js:27212ReactReconciler.mountComponent @ index.js:28027ReactCompositeComponentMixin.mountComponent @ index.js:20111ReactPerf.measure.wrapper @ index.js:27212ReactReconciler.mountComponent @ index.js:28027mountComponentIntoNode @ index.js:25817Mixin.perform @ index.js:31714batchedMountComponentIntoNode @ index.js:25838Mixin.perform @ index.js:31714ReactDefaultBatchingStrategy.batchedUpdates @ index.js:22892batchedUpdates @ index.js:29885ReactMount._renderNewRootComponent @ index.js:25973ReactPerf.measure.wrapper @ index.js:27212ReactMount.render @ index.js:26062ReactPerf.measure.wrapper @ index.js:272121../components/AppContainer.jsx @ index.js:14s @ index.js:1e @ index.js:1(anonymous function)

**Comment by seamc** [comment]
The Material-ui ThemeManager should be in the App.jsx

Within App.jsx:

var ThemeManager = require('material-ui/lib/styles/theme-manager')();

let App = React.createClass({
  childContextTypes: {
    muiTheme: React.PropTypes.object
  },
  getChildContext() {
    return {
      muiTheme: ThemeManager.getCurrentTheme()
    };
  }

// ... etc

};
module.exports = App;

**Comment by banderson** [comment]
@seamc thanks for the reply! I didn't know ThemeManager was a thing I needed to account for in there. Is this new? It was working for me before. Anyway, I've added a patch release for this, and just release v0.4.2 on NPM that should have this fix. Thanks for the help!

**Comment by mtbvang** [comment]
Thanks for the help guys. I noticed that reverting material-ui dependency to "^0.7.5" got me around the error. I guess the ThemeManager is new to MUI 0.8.

**Comment by banderson** [comment]
Closing this for now, see #40 for the current state of the Material UI ThemeManager implementation
