### ISSUE TITLE
Browserify Error { [Error: Cannot find module 'react' from

### ISSUE THREAD

**Issue by EwanValentine** [banderson/generator-flux-react#36]
I keep getting 

```
Browserify Error { [Error: Cannot find module 'react' from

```
along with loads of other similar errors when I run ```$ sudo npm start ``` or ```$ sudo npm run dev```

**Comment by bdeezz** [comment]
Try $ npm install react

**Comment by banderson** [comment]
@EwanValentine why are you `sudo`ing those npm commands? It seems like that might have something to do with it (path problems, etc)
