### ISSUE TITLE
Generated files do not comply with projects .eslintrc rules.

### ISSUE THREAD

**Issue by William-Ritson** [banderson/generator-flux-react#38]
When I create a new project and run ESLint through Atom's linter-eslint plugin the first thing I notice is that the .eslintrc contains 3 rules that no longer exist in the current version of ESLint. Perhaps the problem is that I am using a different version of .eslint than the developer.

After removing these rules I find that many of the files contain a large number of linter errors. The project does not seem to comply with its own set of linting rules. 

I noticed that the gulp file does not seem to have a task for linting the project. This makes me wonder if ESLint is actually meant to be used with this project and if not why it contains the .eslintrc file.

**Comment by banderson** [comment]
@William-Ritson I totally hear ya, so I just pushed a fix. I didn't set up the `gulp lint` task to run by default, but you can run that manually to see the results. The source code should be cleaned up to no longer violate the included rules as well. Let me know if you run into any issues with this. 

Your changes are included in the just-published 0.4.5 version.
