### ISSUE TITLE
Despite argument passed to, yo flux:store StoreName, creates conflict with 'BaseStore'

### ISSUE THREAD

**Issue by dgautsch** [banderson/generator-flux-react#39]
No matter what parameter you pass to this generator, it thinks there is a conflict with BaseStore. Is this by design? It seems it's not reading the argument passed to it. Is this by design?

**Comment by banderson** [comment]
@dgautsch that is definitely not by design!

I just published a change included in the 0.4.5 release, let me know if you have any problems after the upgrade!
