### ISSUE TITLE
a warning and an error on an out of the box react-bootstrap

### ISSUE THREAD

**Issue by lmessinger** [banderson/generator-flux-react#41]
arning: Each child in an array or iterator should have a unique "key" prop. Check the render method of TaskList. See https://fb.me/react-warning-keys for more information.

and when creating a task and checking it:

index.js:21454 Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

any ideas on how to fix it?

thanks

**Comment by weshoke** [comment]
I see the same.  Also, when interacting with the default app, I see:

```
Uncaught TypeError: Cannot read property 'getChecked' of undefined
```

**Comment by weshoke** [comment]
http://stackoverflow.com/questions/28519287/what-does-only-a-reactowner-can-have-refs-mean

**Comment by weshoke** [comment]
Not sure how to fix this yet, but `npm list` shows:

```
├─┬ react@0.13.3
│ └─┬ envify@3.4.0
│   ├─┬ jstransform@10.1.0
│   │ ├── base62@0.1.1
│   │ ├── esprima-fb@13001.1001.0-dev-harmony-fb
│   │ └─┬ source-map@0.1.31
│   │   └── amdefine@1.0.0
│   └── through@2.3.8
├─┬ react-bootstrap@0.25.2
│ ├─┬ babel-runtime@5.8.25
│ │ └── core-js@1.2.1
│ ├── classnames@2.1.5
│ ├── dom-helpers@2.4.0
│ ├── keycode@2.1.0
│ ├── lodash@3.10.1
│ ├── react@0.13.3 extraneous
│ ├─┬ react-overlays@0.4.4
│ │ ├── react-prop-types@0.2.2
│ │ └─┬ warning@2.0.0
│ │   └─┬ envify@3.4.0
│ │     ├─┬ jstransform@10.1.0
│ │     │ ├── base62@0.1.1
│ │     │ ├── esprima-fb@13001.1001.0-dev-harmony-fb
│ │     │ └─┬ source-map@0.1.31
│ │     │   └── amdefine@1.0.0
│ │     └── through@2.3.8
```

There are 2 versions of `react`

**Comment by weshoke** [comment]
Yep, that's it.  If you delete `node_modules/react-bootstrap/node_modules/react` and rebuild the dist, everything will work.  Now to figure out why is was there in the first place.  Maybe it's an order of dependencies issue?

**Comment by weshoke** [comment]
If you update `npm`, the dependencies are handled in quite a different way.  `node_modules` don't have their own `node_modules` folders, so there's no duplicated react dependency and everything works as expected.  The only error is a 404 No Favicon resource found.

**Comment by banderson** [comment]
@weshoke Ahhh, I see what you mean now. This is definitely annoying. It's tricky because on npm v3 this should work as intended out of the box, but for anyone on a previous version, the solution is to run `npm dedupe`  :/   I really wish there was an easier way to have a consistent fix

**Comment by banderson** [comment]
Also, see this existing issue for when this whole issue began: https://github.com/banderson/generator-flux-react/issues/12
