### ISSUE TITLE
Run errors

### ISSUE THREAD

**Issue by anned20** [banderson/generator-flux-react#46]
When I'm trying to run this with: `npm run dev` I get a lot of errors about missing modules. What did I do wrong? I did `npm install` and `bower install` but it didn't change anything.

Edit: The errors seem to be in the gulp/tasks/ folder

**Comment by banderson** [comment]
hmmm... It sounds like something broke during the initial install. Can you `rm -rf ./node_modules` and run `nom install` again? Post your error messages here if you still run into issues.

**Comment by anned20** [comment]
I run Windows, so I don't think that is going to work

**Comment by banderson** [comment]
Ah, ok you can just delete the directory in the UI if that works! I forget the windows equivalent for `rm`

**Comment by darkyen** [comment]
For me it creates the package.json without any modules :<  not cool man!
